### ISSUE TITLE
新增【计算控件】类型组件

### ISSUE THREAD

**Issue by luofann** [TencentBlueKing/bk-lesscode#804]
【问题描述】

在高级控件分组下，新增计算控件
![image](https://user-images.githubusercontent.com/44999219/222312931-a490364f-a91d-4618-8fc2-0b0713fd08c3.png)

核心配置项如下，除了没有【是否唯一】外，其他配置项与一期中基础字段一致。

1、【计算类型】：支持选择数值计算/时间日期

![image](https://user-images.githubusercontent.com/44999219/222312976-4bd3afa6-83e8-4842-b2c1-c056ae017aa3.png)

1.1当选计算类型】选择时间日期时，将计算（结束日期-开始日期）的间隔时间
【开始日期/结束日期】支持选择表单中的日期类型的表单字段、指定日期、创建时间、最近更新日期
![image](https://user-images.githubusercontent.com/44999219/222313010-8d195154-979c-465b-97fa-4c5297d92ac2.png)

【结果精确度】：计算的结果将会按照选择的精确度进行展示；例如选择精确度为小时的时候，则结果为46天19小时
![image](https://user-images.githubusercontent.com/44999219/222313033-ca8fa26a-5fef-482b-8af3-519fc1caf39f.png)

【日期字段未精确到时间时，默认为】：当【开始日期】/【结束日期】字段中选择的字段为日期字段且【结果精确度】选择为小时/分钟时，显示该配置项。
![image](https://user-images.githubusercontent.com/44999219/222313061-dd32cf64-2ebe-453d-864a-b86c2dbb2311.png)

2、当【计算类型】选择数值计算时
![image](https://user-images.githubusercontent.com/44999219/222313088-8238254b-56e5-4a31-8217-d6b578a693a6.png)

【计算公式】枚举值为：求和、平均值、中位数、乘积、最大值、最小值、自定义；当【计算公式】选择自定义时，【计算字段】隐藏；：当【计算公式】选择自定义时，下方出现文字链接「配置公式」；
![image](https://user-images.githubusercontent.com/44999219/222313107-41e0bbff-b0a1-4eca-86e6-326009057fa3.png)

【计算字段】：当【计算公式】非自“自定义”时，能够选择到表单中（包括表格）内所有数值类型的字段，主表字段可以多选，表格字段只能选择一个；若【计算公式】为自定义时，只能选择到主表中数据
![image](https://user-images.githubusercontent.com/44999219/222313124-6f4136eb-4ba7-4489-ae53-9d1a1d4101ce.png)

「配置公式」：点击该文字弹出气泡弹窗，支持用户选择主表字段，输入+—*/（）配置计算公式

![image](https://user-images.githubusercontent.com/44999219/222313159-94806116-91e4-41aa-b130-e7477ced20e8.png)

单位：用于配置计算控件的结果单位，支持将单位设为前缀/后缀；

保留小数位数：支持用户配置计算结果的小数位数

**Comment by sundytt** [comment]
![image](https://user-images.githubusercontent.com/30256396/226503875-07a54a20-93f6-41b9-889d-74d01c5607a0.png)
